spring:
  datasource:
    url: jdbc:mysql://springstudy.cgllngfx5zdm.ap-northeast-2.rds.amazonaws.com:3306/SoccerCollection
    username: admin
    password: dla23689!!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30

  jpa:
    generate-ddl: true
    hibernate: # create: drop-create
      ddl-auto: update
      show-sql: true